PlantPalace/Areas/Admin/Controllers/CouponController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PlantPalace.DataAccess.Repository.IRepository;
using PlantPalace.Models;
using PlantPalace.Models.ViewModels;
using PlantPalace.Utility;

namespace PlantPalace.Areas.Admin.Controllers
{
	[Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]

    public class CouponController : Controller
	{
		private readonly IUnitOfWork _unitOfWork;
		public CouponController(IUnitOfWork unitOfWork)
		{
			_unitOfWork = unitOfWork;

		}
		public IActionResult Index()
		{

			CouponVM vm = new()
			{
				Coupons = _unitOfWork.Coupon.GetALL().ToList(),
				CouponsData = _unitOfWork.CouponsData.GetALL().ToList(),
			};
			return View(vm);
		}

		public IActionResult Create()
		{
			return View();
		}
		[HttpPost]
		public IActionResult Create(Coupon model)
		{


			if (ModelState.IsValid)
			{
				if(DateTime.UtcNow >= model.ExpiryDate)
				{
					ModelState.AddModelError("ExpiryDate", "Expiry Data Must Be Grater Than the Current Date");
                    return View(model);

                }
                model.PublishDate = DateTime.UtcNow;
				_unitOfWork.Coupon.Add(model);
				_unitOfWork.Save();
				TempData["success"] = "Coupon Created Successfully";
				return RedirectToAction("Index");
			}
			ModelState.AddModelError("Name", "name is required");
			TempData["error"] = "Something went wrong ";

			return View(model);
		}




		public IActionResult Edit(int? id)
		{
			if (id == null || id == 0)
			{
				return NotFound();
			}

			Coupon? coupon = _unitOfWork.Coupon.Get(u => u.Id == id);
			if (coupon == null)
			{
				return NotFound();
			}
			return View(coupon);
		}
		[HttpPost]
		public IActionResult Edit(Coupon model)
		{
			if (ModelState.IsValid)
			{
				_unitOfWork.Coupon.Update(model);
				_unitOfWork.Save();
				TempData["success"] = "Coupen Edited Successfully";
				return RedirectToAction("Index");
			}
			return View();
		}


		public IActionResult Delete(int? id)
		{
			if (id == null || id == 0)
			{
				return NotFound();
			}

			Coupon? coupon = _unitOfWork.Coupon.Get(u => u.Id == id);
			if (coupon == null)
			{
				return NotFound();
			}
			return View(coupon);
		}


		[HttpDelete, ActionName("Delete")]
		public IActionResult DeletePost(int? id)
		{
			if (id == 0)
			{
				return NotFound();
			}

			var coupon = _unitOfWork.Coupon.Get(u => u.Id == id);

			if (coupon == null)
				return NotFound();


			_unitOfWork.Coupon.Remove(coupon);
			_unitOfWork.Save();
			TempData["success"] = "Coupon Deleted Successfully";
			return RedirectToAction("Index");
		}
	}
}

PlantPalace/Areas/Admin/Controllers/OfferController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PlantPalace.DataAccess.Repository;
using PlantPalace.DataAccess.Repository.IRepository;
using PlantPalace.Models;
using PlantPalace.Models.ViewModels;
using PlantPalace.Utility;

namespace PlantPalace.Areas.Admin.Controllers
{
	[Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]

    public class OfferController : Controller
	{
		private readonly IUnitOfWork _unitOfWork;
		private readonly IWebHostEnvironment _webHostEnvironment;
		public OfferController(IUnitOfWork unitOfWork, IWebHostEnvironment webHostEnvironment)
		{
			_unitOfWork = unitOfWork;
			_webHostEnvironment = webHostEnvironment;

		}
		public IActionResult Index()
		{
			var Offers = _unitOfWork.Offer.GetALL();
			return View(Offers);
		}

		public IActionResult Upsert(int? id)
		{
			var vm = new OfferVM();
			vm.Offer = new Offer();
			if(id != null && id != 0)
			{
				vm.Offer = _unitOfWork.Offer.Get(u => u.Id == id);

			}
			vm.Products = _unitOfWork.Product.GetALL(incluedProperties: "Category").ToList(); ;
			return View(vm);
		}
		[HttpPost]
		public IActionResult Upsert(OfferVM model, string? newfile,List<int> selectedProducts)
		{
			string wwwRootPath = _webHostEnvironment.WebRootPath;

			if (newfile != null)
			{


				if (!string.IsNullOrEmpty(model.Offer.ImageUrl))
				{
					var oldImagePath = Path.Combine(wwwRootPath, model.Offer.ImageUrl.TrimStart('\\'));

					if (System.IO.File.Exists(oldImagePath))
					{
						System.IO.File.Delete(oldImagePath);
					}
				}
				model.Offer.AddedDate = DateTime.UtcNow;
				model.Offer.ImageUrl = @"\Images\Offers\" + newfile;
			}
			if(model.Offer.OfferName == null)
			{
				ModelState.AddModelError("OfferName", "Plaese Enter the Offer Name");
			}
			else
			{
				model.Offer.OfferUrl = "/customer/home/ProductList?offer="+model.Offer.OfferName;

            }
			
			if (ModelState.IsValid)
			{
				if(selectedProducts == null)
				{
					ModelState.AddModelError("selectedProducts", "select any product atleast one in manitatory");
                    return View();

                }
				else
				{
					foreach(var productid in selectedProducts)
					{
                        var product = _unitOfWork.Product.Get(u => u.Id == productid);
						if(product != null && 100 > model.Offer.OfferPercent)
						{
                            //product.DiscountPrice = (product.Price/100)*(100- model.Offer.OfferPercent);
                            product.DiscountPrice = (double)((decimal)(product.Price / 100) * (100 - (decimal)model.Offer.OfferPercent));

                            product.OfferName = model.Offer.OfferName;
                            _unitOfWork.Product.Update(product);
                        }
						else
						{
							ModelState.AddModelError("OfferPrice", "Change Offer Price is not considerable");
                            return View();

                        }

                    }
				}
                
				if(model.Offer.Id != 0 && model.Offer.Id != null)
				{
                    _unitOfWork.Offer.Update(model.Offer);
                    TempData["success"] = "Offer Edited Successfully";

                }
				else
				{
                    _unitOfWork.Offer.Add(model.Offer);
                    TempData["success"] = "Offer Created Successfully";
                }
                

                _unitOfWork.Save();
				return RedirectToAction("Index");
			}
			ModelState.AddModelError("Name", "name is required");
			return View();
		}

		[HttpPost]
		public IActionResult CropAndSave(string FORfilename, IFormFile? file)
		{
			string wwwRootPath = _webHostEnvironment.WebRootPath;
			if (file != null)
			{
				string filename = Guid.NewGuid().ToString() + "_" + FORfilename;
				string productPath = wwwRootPath + @"\Images\Offers\";


				ImageCrop crop = new ImageCrop();
				crop.CropBanner(Path.Combine(productPath, filename), file);

				return Json(new { message = "OK", filename = filename.ToString() });
			}

			return Json(new { message = "ERROR" });
		}



		public IActionResult Delete(int? id)
		{
			if (id == null || id == 0)
			{
				return NotFound();
			}

			Offer? Offer = _unitOfWork.Offer.Get(u => u.Id == id,incluedProperties: "Product");
			if (Offer == null)
			{
				return NotFound();
			}
			return View(Offer);
		}


		[HttpDelete, ActionName("Delete")]
		public IActionResult DeletePost(int? id)
		{
			if (id == null || id == 0)
			{
				return NotFound();
			}

			var Offer = _unitOfWork.Offer.Get(u => u.Id == id);

			if (Offer == null)
				return NotFound();

            /*var product = _unitOfWork.Product.Get(u => u.Id == Offer.ProductId);
			product.DiscountPrice = 0;
			_unitOfWork.Product.Update(product);*/

            if (Offer.OfferName != null)
            {
                var products = _unitOfWork.Product.GetALL(u => u.OfferName != null)
                                               .AsEnumerable() // Materialize data
                                               .Where(u => u.OfferName.Normalize() == Offer.OfferName.Normalize())
                                               .ToList();

                foreach (var product in products)
                {
                    product.DiscountPrice = 0;
                    product.OfferName = "";

                    _unitOfWork.Product.Update(product);
                }
            }

            _unitOfWork.Offer.Remove(Offer);
			_unitOfWork.Save();
			//TempData["success"] = "Offer Deleted Successfully";
			return Json(new {message = "Offer Deleted Successfully" });
		}
	}
}

PlantPalace/Areas/Admin/Controllers/UserController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using PlantPalace.DataAccess.Repository.IRepository;
using PlantPalace.Models;
using PlantPalace.Utility;
using System.Data;

namespace BulkyBookWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class UserController : Controller
    {
        private readonly UserManager<IdentityUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly IUnitOfWork _unitOfWork;
        public UserController(UserManager<IdentityUser> userManager, IUnitOfWork unitOfWork, RoleManager<IdentityRole> roleManager) {
            _unitOfWork = unitOfWork;
            _roleManager = roleManager;
            _userManager = userManager;
        }
        public IActionResult Index() 
        {
            return View();
        }





        #region API CALLS

        [HttpGet]
        public IActionResult GetAll()
        {
            List<ApplicationUser> objUserList = _unitOfWork.ApplicationUser.GetALL().ToList();

            foreach(var user in objUserList) {

                user.Role=  _userManager.GetRolesAsync(user).GetAwaiter().GetResult().FirstOrDefault();
            }

            return Json(new { data = objUserList });
        }


        [HttpPost]
        public IActionResult LockUnlock([FromBody]string id)
        {

            var objFromDb = _unitOfWork.ApplicationUser.Get(u => u.Id == id);
            if (objFromDb == null) 
            {
                return Json(new { success = false, message = "Error while Locking/Unlocking" });
            }

            if(objFromDb.LockoutEnd!=null && objFromDb.LockoutEnd > DateTime.Now) {
                //user is currently locked and we need to unlock them
                objFromDb.LockoutEnd = DateTime.Now;
            }
            else {
                objFromDb.LockoutEnd = DateTime.Now.AddYears(1000);
            }
            objFromDb.LockoutEnabled = !objFromDb.LockoutEnabled;

            _unitOfWork.ApplicationUser.Update(objFromDb);
            _unitOfWork.Save();
            string MSG;
            if (objFromDb.LockoutEnabled)
            {
                MSG = "Blocked Successful";
            }
            else
            {
                MSG = "unblocked Successful";

            }
            return Json(new { success = true, message = MSG });
        }

        #endregion
    }
}

PlantPalace/Areas/Customer/Controllers/WishListController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using PlantPalace.DataAccess.Repository.IRepository;
using PlantPalace.Models;
using PlantPalace.Models.ViewModels;
using PlantPalace.Utility;
using Stripe.Checkout;
using System.Security.Claims;

namespace PlantPalaceWeb.Areas.Customer.Controllers
{
    [Area("Customer")]
    [Authorize]
    public class WishListController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        [BindProperty]
        public WishListVM WishListVM { get; set; }
        public WishListController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            WishListVM = new WishListVM()
            {

                WishLists = _unitOfWork.WishList.GetALL(u => u.userId == claim.Value, incluedProperties: "Product"),
            };

            return View(WishListVM);
        }


        [HttpGet]
        [Authorize]
        public IActionResult AddORremove(int ProductId)
        {
            WishList listitem = new WishList()
            {
                ProductId = ProductId
            };


            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            listitem.userId = claim.Value;



            WishList listDb =
                _unitOfWork.WishList.Get(u => u.userId == claim.Value && u.ProductId == listitem.ProductId);

            if (listDb == null)
            {
                _unitOfWork.WishList.Add(listitem);
            }
            else
            {
                _unitOfWork.WishList.Remove(listDb);


            }

            _unitOfWork.Save();

            return RedirectToAction(nameof(Index));


        }
    }
}

PlantPalace/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PlantPalace</title>
    <link runat="server" rel="shortcut icon" href="~/icons8-leaf-64.png" type="image/x-icon" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/PlantPalace.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.7.1.js" integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4=" crossorigin="anonymous"></script>
    <script src="https://cdn.tiny.cloud/1/x44iexamq3gkxmpp6uffkgtcvba2zfo7sth95d66no54cdd4/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/croppie/2.6.5/croppie.min.css" integrity="sha512-zxBiDORGDEAYDdKLuYU9X/JaJo/DPzE42UubfBw9yg8Qvb2YRRIQ8v4KsGHOx2H1/+sdSXyXxLXv5r7tHc9ygg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdn.datatables.net/1.13.3/css/jquery.dataTables.min.css" />

    @await RenderSectionAsync("head", required: false)

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow mb-3">
            <div class="container-fluid text-nowrap">
                <a class="navbar-brand d-md-none d-lg-block d-sm-block   text-black" asp-area="" asp-controller="Home" asp-action="Index">
                    <h3 class="text-white ms-5">PlantPalace</h3>
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Customer" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (!User.IsInRole(SD.Role_Admin))
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="Customer" asp-controller="Home" asp-action="ProductList">Shop Now</a>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Admin" asp-controller="Order" asp-action="Index">Orders</a>
                        </li>

                        @if (!User.IsInRole(SD.Role_Admin))
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="Customer" asp-controller="Cart" asp-action="Index">
                                    <i class="bi bi-cart"></i> Cart
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="Customer" asp-controller="WishList" asp-action="Index">
                                    <i class="bi bi-heart"></i> Wishlist
                                </a>
                            </li>
                        }

                        @if (User.IsInRole(SD.Role_Admin))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Content Managment
                                </a>
                                <ul class="dropdown-menu">
                                    <li class="nav-item">
                                        <a class="dropdown-item" asp-area="Identity" asp-page="/Account/Register">Create User</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="dropdown-item" asp-area="Admin" asp-controller="User" asp-action="Index">Manage User</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="dropdown-item" asp-area="Admin" asp-controller="Order" asp-action="ReturnList">Return Request</a>
                                    </li>
                                    <li><hr class="dropdown-divider"></li>

                                    <li class="nav-item">
                                        <a class="dropdown-item" asp-area="Admin" asp-controller="Category" asp-action="Index">Category</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="dropdown-item" asp-area="Admin" asp-controller="Product" asp-action="Index">Product</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="dropdown-item" asp-area="Admin" asp-controller="Offer" asp-action="Index">Offer Manegement</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="dropdown-item" asp-area="Admin" asp-controller="Coupon" asp-action="Index">Coupon Manegement</a>
                                    </li>

                                </ul>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>
    <footer class="border-top footer bg-primary text-muted fixed-bottom">
        <div class="text-center">
            Made with <i class="bi bi-code-slash"></i> by Muhammed Fahmi
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>

    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="//cdn.datatables.net/1.13.3/js/jquery.dataTables.min.js" asp-append-version="true"></script>
    @* <script src="https://cdn.tiny.cloud/1/g28lhnxtlihu4l4a381gw7tz47voznshwbi10lmsvlekrfme/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script> *@
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/croppie/2.6.5/croppie.min.js" integrity="sha512-Gs+PsXsGkmr+15rqObPJbenQ2wB3qYvTHuJO6YJzPe/dTLvhy0fmae2BcnaozxDo5iaF8emzmCZWbQ1XXiX2Ig==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

PlantPalace/Views/Shared/_Notification.cshtml
@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]');
    </script>
}
@if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["error"]');
    </script>
}

PlantPalace/Views/Shared/_ProductListPartial.cshtml
@model List<Product>
@if (Model.Count() == 0)
{
    <div class="col-12 d-flex justify-content-center align-items-center flex-column">
        <img src="~/Images/notAndDeadIcon.png">
        <h1>Product Not Available</h1>
        <p>on this filter</p>
        <button id="refresh" class="btn btn-primary">Refresh</button>
    </div>
}
else
{
    <ul class="product_list mb-2 list">
        @foreach (var product in Model)
        {
            <li class="product_item  ml-md-4 mb-3 rounded">
                @if (product.Stock == 0)
                {
                    <div class="product_sale">
                        <p>Out Of Stock</p>
                    </div>
                }

                <div class="product_image d-flex justify-content-center align-items-center flex-wrap">
                    <a asp-action="Details" asp-route-productId="@product.Id"><img id="img" src="@product.ImageUrl" alt=""></a>
                    <div class="product_buttons">
                        <button onclick="AddORremove(@product.Id)" class="product_heart"><i class="fa fa-heart"></i></button>
                        <button onclick="AddToCart(@product.Id)" class="add_to_cart"><i class="fa fa-shopping-cart"></i></button>

                    </div>
                </div>
                <div class="product_values">
                    <div class="product_title  text-nowrap overflow-hidden">
                        <h5 style="text-overflow:ellipsis;">@product.Name</h5>
                    </div>
                    <div class="product_price">
                        @if (product.DiscountPrice == 0)
                        {
                            <a href="#">@* <span class="price_old">@product.ListPrice.ToString("c")</span> *@ <span class="price_new">₹@product.Price</span></a>

                        }
                        else
                        {
                            <a href="#"><span class="price_old">₹@product.Price</span> <span class="price_new">₹@product.DiscountPrice</span></a>

                        }
                    </div>
                    <div class="col-12">
                        <div>
                            <a asp-action="Details"
                               asp-route-productId="@product.Id"
                               class="btn btn-primary bg-gradient rounded ">
                                Details
                            </a>
                        </div>
                    </div>
                    <div class="product_buttons">
                        <button onclick="AddORremove(@product.Id)" class="product_heart"><i class="fa fa-heart"></i></button>
                        <button onclick="AddToCart(@product.Id)" class="add_to_cart"><i class="fa fa-shopping-cart"></i></button>
                    </div>
                </div>
            </li>
        }


    </ul>
}
<script>
    document.getElementById('refresh').addEventListener('click', function () {
        // Handle refresh action here
        location.reload(); // This will reload the page, you can replace it with your custom logic
    });
    function AddToCart(productId) {
        var url = "/Customer/Home/AddTOcart?ProductId=" + productId;
        $.ajax({
            url: url,
            type: 'GET',
            success: function (data) {

                toastr.success(data.message);
            }
        });
    }

    function AddORremove(productId) {
        var url = "/Customer/WishList/AddORremove?ProductId=" + productId;
        $.ajax({
            url: url,
            type: 'GET',
            success: function (data) {

                toastr.success("add to wish list successfully");
            }
        });
    }
</script>